{% set version = "1.0.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-coro
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/coro_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/coro/coro_{{ version }}.tar.gz
  sha256: ac755d09207d0249a5c36e01e37bc8002b1452ca7a93108cd7ad601e6f3c4a64

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rlang >=0.4.9
  run:
    - r-base
    - r-rlang >=0.4.9

test:
  commands:
    - $R -e "library('coro')"           # [not win]
    - "\"%R%\" -e \"library('coro')\""  # [win]

about:
  home: https://github.com/r-lib/coro
  license: MIT
  summary: Provides 'coroutines' for R, a family of functions that can be suspended and resumed later on. This includes 'async' functions (which await) and generators (which yield). 'Async' functions are based on the concurrency framework of the 'promises' package. Generators are based on a dependency free iteration protocol
    defined in 'coro' and are compatible with iterators from the 'reticulate' package.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - izahn

# Package: coro
# Title: 'Coroutines' for R
# Version: 1.0.1
# Authors@R: c( person("Lionel", "Henry", ,"lionel@rstudio.com", c("aut", "cre")), person("RStudio", role = "cph") )
# Description: Provides 'coroutines' for R, a family of functions that can be suspended and resumed later on. This includes 'async' functions (which await) and generators (which yield). 'Async' functions are based on the concurrency framework of the 'promises' package. Generators are based on a dependency free iteration protocol defined in 'coro' and are compatible with iterators from the 'reticulate' package.
# Depends: R (>= 3.5.0)
# Imports: rlang (>= 0.4.9)
# Suggests: knitr, later (>= 1.1.0), magrittr (>= 2.0.0), promises, reticulate, rmarkdown, testthat (>= 3.0.0)
# VignetteBuilder: knitr
# License: MIT + file LICENSE
# URL: https://github.com/r-lib/coro
# BugReports: https://github.com/r-lib/coro/issues
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.1.1
# Config/testthat/edition: 3
# NeedsCompilation: no
# Packaged: 2020-12-17 18:55:26 UTC; lionel
# Author: Lionel Henry [aut, cre], RStudio [cph]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2020-12-17 20:10:02 UTC
